import os
from openai import OpenAI
from anthropic import Anthropic
from dotenv import load_dotenv

load_dotenv()

openai_client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
anthropic_client = Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

def ask(prompt, system=None, temperature=0.7, max_tokens=200, provider="openai", model=None):
    """
    Στέλνει ένα prompt στο επιλεγμένο LLM (OpenAI ή Anthropic) και επιστρέφει την απάντηση.
    """
    
    # ------------------ OPENAI ------------------
    if provider.lower() == "openai":
        actual_model = model or "gpt-4o-mini" 
        
        msgs = []
        if system:
            msgs.append({"role": "system", "content": system})
        msgs.append({"role": "user", "content": prompt})
        
        kwargs = {
            "model": actual_model,
            "messages": msgs,
            "temperature": temperature,
            "max_tokens": max_tokens
        }
        
        r = openai_client.chat.completions.create(**kwargs)
        return r.choices[0].message.content

    # ----------------- ANTHROPIC -----------------
    elif provider.lower() == "anthropic":
        actual_model = model or "claude-haiku-4-5-20251001"
        
        msgs = [{"role": "user", "content": prompt}]
        
        kwargs = {
            "model": actual_model,
            "messages": msgs,
            "temperature": temperature,
            "max_tokens": max_tokens
        }
        
        if system:
            kwargs["system"] = system
            
        r = anthropic_client.messages.create(**kwargs)
        return r.content[0].text

    else:
        raise ValueError("Μη υποστηριζόμενος provider. Επίλεξε 'openai' ή 'anthropic'.")
    
# -------- PCTF --------
def create_pctf_prompt(persona:str, context:str, task: str, format:str) -> tuple[str, str]:

    system_prompt = persona.strip()

    user_prompt = f""" Context: {context.strip()}

Task: {task.strip()}

format: {format.strip()}
"""
    
    return system_prompt, user_prompt

# -------- EVAL --------
def prompt_eval(question: str, response: str, criteria: str,  eval_provider: str = "openai", eval_model = "gpt-4o-mini")-> str:

    eval_system = (
        "You are an expert prompt-engineering evaluator.\n"
        "You will receive a QUESTION (the original prompt), a RESPONSE generated by an LLM, and CRITERIA.\n\n"
        "Score EACH dimension defined in the CRITERIA from 1.0 to 5.0 based on the prompt's quality "
        "and how well the generated response reflects it. Provide a brief justification for each score.\n\n"
        "Compute the average as 'score'.\n\n"
        "Return the answer as markdown with an unordered list (bullets) of the average score, "
        "followed by the score and justification for each dimension."
    )

    
    eval_prompt = (
        f"QUESTION:\n{question}\n\n"
        f"RESPONSE:\n{response}\n\n"
        f"CRITERIA:\n{criteria}"
    )

    eval_result = ask(prompt= eval_prompt, system= eval_system, temperature=0, max_tokens=800, provider= eval_provider, model= eval_model)

    return eval_result